### ISSUE TITLE
Retinanet on deepstream error

### ISSUE THREAD

**Issue by KNaudin** [NVIDIA/retinanet-examples#109]
Hello. I've followed the installation for Deepstream 4.0 as the TRT5 branch suggests and was able to run the Deepstream samples. I proceeded with the installation process as explained in the README of this repo.
I then decided to export an engine file on my Jetson TX2 (which works with TRT 5.1) using the cpp API. I configured the 2 config files infer_config_batch1.txt and ds_config_1vid.txt to load my generated engine file, an RTSP stream (which works with the other samples) and my label map.
Please note that both the generated engine and pth file work for inference.
When starting deepstream with my configuration, the following message appears:
`no kernel image is available for execution on the device`
The NVIDIA forums state that this is a version mismatch, but the engine file was generated on the exact machine I'm trying to run deepstream on. Any idea of what I should do ?

**Comment by yashnv** [comment]
which version of deepstream are you using? 4.0.1 or 4.0.2?

**Comment by KNaudin** [comment]
I am using version 4.0.1, as specified [here](https://github.com/NVIDIA/retinanet-examples/tree/TRT5/extras/deepstream#1-download-deepstream-40).

**Comment by yashnv** [comment]
@KNaudin could you please provide some environment info too, like the jetpack version. Also it might be useful to share both the DS config files and the exact command which you are using to replicate this.

**Comment by KNaudin** [comment]
The TX2 has been flashed with JetPack 4.2.2.
## Here's my ds_config_1vid.txt
```
# Copyright (c) 2018 NVIDIA Corporation.  All rights reserved.
#
# NVIDIA Corporation and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA Corporation is strictly prohibited.

[application]
enable-perf-measurement=1
perf-measurement-interval-sec=1

[tiled-display]
enable=0
rows=1
columns=1
width=1280
height=720
gpu-id=0

[source0]
enable=1
type=4
num-sources=1
uri=rtsp://admin:GST4Cam@192.168.1.161
gpu-id=0
cudadec-memtype=0

[streammux]
gpu-id=0
##Boolean property to inform muxer that sources are live
live-source=0
batch-size=1
##time out in usec, to wait after the first buffer is available
##to push the batch even if the complete batch is not formed
batched-push-timeout=40000
## Set muxer output width and height
width=1920
height=1080
##Enable to maintain aspect ratio wrt source, and allow black borders, works
##along with width, height properties
enable-padding=0
nvbuf-memory-type=0

[sink0]
enable=1
type=3
#1=mp4 2=mkv
container=1
#1=h264 2=h265 3=mpeg4
## only SW mpeg4 is supported right now.
codec=3
sync=1
bitrate=80000000
output-file=out.mp4
source-id=0

[sink1]
enable=1
#Type - 1=FakeSink 2=EglSink 3=File
type=5
sync=1
source-id=0
gpu-id=0
qos=0
nvbuf-memory-type=0
overlay-id=1


[osd]
enable=1
gpu-id=0
border-width=2
text-size=12
text-color=1;1;1;1;
text-bg-color=0.3;0.3;0.3;1
font=Arial
show-clock=0
clock-x-offset=800
clock-y-offset=820
clock-text-size=12
clock-color=1;0;0;0

# config-file property is mandatory for any gie section.
# Other properties are optional and if set will override the properties set in
# the infer config file.
[primary-gie]
enable=1
gpu-id=0
model-engine-file=/home/nvidia/Retinanet/engines/XXXX_1920x1080_TX2.engine
batch-size=1
#Required by the app for OSD, not a plugin property
bbox-border-color0=1;0;0;1
bbox-border-color1=0;1;1;1
bbox-border-color2=0;0;1;1
bbox-border-color3=0;1;0;1
interval=4
gie-unique-id=1
nvbuf-memory-type=0
config-file=infer_config_batch1.txt
```

## Here's my infer_config_batch1.txt
```
# Copyright (c) 2018 NVIDIA Corporation.  All rights reserved.
# NVIDIA Corporation and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA Corporation is strictly prohibited.

# Following properties are mandatory when engine files are not specified:
#   int8-calib-file(Only in INT8)
#   Caffemodel mandatory properties: model-file, proto-file, output-blob-names
#   UFF: uff-file, input-dims, uff-input-blob-name, output-blob-names
#   ONNX: onnx-file
#
# Mandatory properties for detectors:
#   parse-func, num-detected-classes,
#   custom-lib-path (when parse-func=0 i.e. custom),
#   parse-bbox-func-name (when parse-func=0)
#
# Optional properties for detectors:
#   enable-dbscan(Default=false), interval(Primary mode only, Default=0)
#
# Mandatory properties for classifiers:
#   classifier-threshold, is-classifier
#
# Optional properties for classifiers:
#   classifier-async-mode(Secondary mode only, Default=false)
#
# Optional properties in secondary mode:
#   operate-on-gie-id(Default=0), operate-on-class-ids(Defaults to all classes),
#   input-object-min-width, input-object-min-height, input-object-max-width,
#   input-object-max-height
#
# Following properties are always recommended:
#   batch-size(Default=1)
#
# Other optional properties:
#   net-scale-factor(Default=1), network-mode(Default=0 i.e FP32),
#   model-color-format(Default=0 i.e. RGB) model-engine-file, labelfile-path,
#   mean-file, gie-unique-id(Default=0), offsets, gie-mode (Default=1 i.e. primary),
#   custom-lib-path, network-mode(Default=0 i.e FP32)
#
# The values in the config file are overridden by values set through GObject
# properties.

[property]
gpu-id=0
net-scale-factor=0.017352074
offsets=123.675;116.28;103.53
#onnx-file=/home/nvidia/Retinanet/onnx/XXXX_1920x1080.onnx
model-engine-file=/home/nvidia/Retinanet/engines/XXXX_1920x1080_TX2.engine
labelfile-path=/home/nvidia/Retinanet/assets/labels/XXXX_labels.txt
batch-size=1
## 0=FP32, 1=INT8, 2=FP16 mode
network-mode=2
num-detected-classes=14
interval=0
gie-unique-id=1
parse-func=0
is-classifier=0
output-blob-names=boxes;scores;classes
parse-bbox-func-name=NvDsInferParseRetinaNet
custom-lib-path=libnvdsparsebbox_retinanet.so
#enable-dbscan=1


[class-attrs-all]
threshold=0.5
group-threshold=0
## Set eps=0.7 and minBoxes for enable-dbscan=1
#eps=0.2
##minBoxes=3
#roi-top-offset=0
#roi-bottom-offset=0
detected-min-w=4
detected-min-h=4
#detected-max-w=0
#detected-max-h=0

## Per class configuration
#[class-attrs-2]
#threshold=0.6
#eps=0.5
#group-threshold=3
#roi-top-offset=20
#roi-bottom-offset=10
#detected-min-w=40
#detected-min-h=40
#detected-max-w=400
#detected-max-h=800
```

I have compiled `nvdsparsebbox_retinanet.cpp` in the same folder, giving me a .so file.
The command I run is `LD_PRELOAD=libnvdsparsebbox_retinanet.so deepstream-app -c ds_config_1vid.txt`

Here are my exact logs:
```
Opening in BLOCKING MODE 

Using winsys: x11 
Creating LL OSD context new
cb_sourcesetup set 100 latency

Runtime commands:
        h: Print this help
        q: Quit

        p: Pause
        r: Resume


**PERF: FPS 0 (Avg)
**PERF: 0.00 (0.00)
WARNING from src_bin_muxer: Rounding muxer output height to the next multiple of 4: 1084
Debug info: /dvs/git/dirty/git-master_linux/deepstream/sdk/src/gst-plugins/gst-nvmultistream/gstnvstreammux.c(2102): gst_nvstreammux_change_state (): /GstPipeline:pipeline/GstBin:multi_src_bin/GstNvStreamMux:src_bin_muxer
** INFO: <bus_callback:189>: Pipeline ready

** INFO: <bus_callback:175>: Pipeline running

Opening in BLOCKING MODE 
NvMMLiteOpen : Block : BlockType = 261 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 261 
** INFO: <bus_callback:175>: Pipeline running

Creating LL OSD context new
NvMMLiteOpen : Block : BlockType = 4 
===== NVMEDIA: NVENC =====
NvMMLiteBlockCreate : Block : BlockType = 4 
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: no kernel image is available for execution on the device
Aborted
```

I've also tried with a non-self trained PyTorch model, the ResNet50 that can be found in the release files of this repo. It gives me the same results.

**Comment by yashnv** [comment]
@KNaudin change [this line](https://github.com/NVIDIA/retinanet-examples/blob/TRT5/extras/deepstream/deepstream-sample/CMakeLists.txt#L20) from `sm_70` to `sm_62`.

**Comment by KNaudin** [comment]
That did the trick ! Thanks a lot.
