### ISSUE TITLE
Cuda error when trying to run the examples.

### ISSUE THREAD

**Issue by topteulen** [NVIDIA/retinanet-examples#190]
Hey im getting a RuntimeError: CUDA error: no kernel image is available for execution on the device (multi_tensor_apply at csrc/multi_tensor_apply.cuh:104) when trying to run the retinanet training
i ran 
odtk train retinanet_rn18fpn.pth --classes 1 --iters 1000 --val-iters 100 --lr 0.03 --images /mnt/cocodata/images/ --annotations /mnt/cocodata/annotations/train.json --val-annotations /mnt/cocodata/annotations/val.json --backbone ResNet18FPN
this didnt work. I also tried with the standard example run on the github but it also doesnt work
I have a Nvidia GTX 970 and am running Ubuntu 20.04. Here is some more information about my setup

![Screenshot from 2020-05-04 15-33-48](https://user-images.githubusercontent.com/33281957/80971976-ce074480-8e1d-11ea-8309-2d70975f3dd6.png)
 
my docker version is: Docker version 19.03.8, build afacb8b7f0
and i tried running on the image: docker run --gpus all --ipc=host -it  nvcr.io/nvidia/pytorch:19.10-py3
and i also have tried on the image: docker run --gpus all --ipc=host -it nvcr.io/nvidia/pytorch:20.03-py3

oh and i had a friend follow my exact same steps with installation etc and with him it worked. Only difference being that he has an NVIDIA GTX 1080

Does anyone know what the problem is and how i can fix it?
thnx for taking the effort to help in advance!

**Comment by yashnv** [comment]
Hello, we don't support Maxwell architectures by default.
You can add `'-gencode=arch=compute_52,code=sm_52'` to [this line](https://github.com/NVIDIA/retinanet-examples/blob/master/setup.py#L16) and do a pip install again.

Your friend has Pascal arch (sm_61), which is supported through setuptools, so it works in that case.

**Comment by topteulen** [comment]
hi, i followed your instructions but i am getting another, maybe related error?

Traceback (most recent call last):
  File "/opt/conda/bin/odtk", line 11, in <module>
    load_entry_point('odtk', 'console_scripts', 'odtk')()
  File "/workspace/retinanet/retinanet/main.py", line 238, in main
    worker(0, args, 1, model, state)
  File "/workspace/retinanet/retinanet/main.py", line 180, in worker
    regularization_l2=args.regularization_l2, rotated_bbox=args.rotated_bbox, absolute_angle=args.absolute_angles)
AttributeError: 'Namespace' object has no attribute 'absolute_angles'
[E ProcessGroupNCCL.cpp:284] NCCL watchdog thread terminated

**Comment by yashnv** [comment]
This looks like a naming bug, just pushed a patch. Can you try the new change, and do a pip install again?

**Comment by topteulen** [comment]
Traceback (most recent call last):
  File "/opt/conda/bin/odtk", line 11, in <module>
    load_entry_point('odtk', 'console_scripts', 'odtk')()
  File "/workspace/retinanet/retinanet/main.py", line 238, in main
    worker(0, args, 1, model, state)
  File "/workspace/retinanet/retinanet/main.py", line 180, in worker
    regularization_l2=args.regularization_l2, rotated_bbox=args.rotated_bbox, absolute_angle=args.absolute_angle)
  File "/workspace/retinanet/retinanet/train.py", line 68, in train
    absolute_angle=absolute_angle)
TypeError: __init__() got an unexpected keyword argument 'absolute_angle'
[E ProcessGroupNCCL.cpp:284] NCCL watchdog thread terminated

still errors with the absolute_angle this time not an naming error but a keyword error

**Comment by yashnv** [comment]
The trainer was calling data iterator incorrectly, pushed another patch, retry again.

**Comment by topteulen** [comment]
thnx, it is working now!! so i want to thank you for your time and effort!

oh one small thing, its posting this warning 
/opt/conda/lib/python3.6/site-packages/torch/optim/lr_scheduler.py:201: UserWarning: Please also save or load the state of the optimzer when saving or loading the scheduler.
  warnings.warn(SAVE_STATE_WARNING, UserWarning)

but it doesn't seem to influence the training or anything so that's fine.
again thank you for the help!
