### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by monocongo** [NVIDIA/retinanet-examples#44]
When I attempt to convert my fine-tuned model to a TensorRT engine I get an out-of-memory error:
```bash
root@b5f4a13b6ad1:/workspace# retinanet export model.pth engine.plan
Loading model from model.pth...
     model: RetinaNet
  backbone: ResNet50FPN
   classes: 1, anchors: 9
Model loaded from model.pth...
type(model): <class 'retinanet.model.Model'>
model.stride: 128
Exporting to ONNX...
Traceback (most recent call last):
  File "/opt/conda/bin/retinanet", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/retinanet/main.py", line 197, in main
    worker(0, args, 1, model, state)
  File "/opt/conda/lib/python3.6/site-packages/retinanet/main.py", line 178, in worker
    exported = model.export(input_size, args.batch, precision, calibration_files, args.calibration_table, args.verbose, onnx_only=onnx_only, opset=args.opset)
  File "/opt/conda/lib/python3.6/site-packages/retinanet/model.py", line 226, in export
    torch.onnx.export(self.cuda(), zero_input, onnx_bytes, *extra_args)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/__init__.py", line 24, in export
    return utils.export(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 108, in export
    _retain_param_name=_retain_param_name)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 315, in _export
    _retain_param_name)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 234, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/opt/conda/lib/python3.6/site-packages/torch/onnx/utils.py", line 201, in _trace_and_get_graph_from_model
    trace, torch_out = torch.jit.get_trace_graph(model, args, _force_outplace=True)
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py", line 215, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace, return_inputs)(*args, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py", line 272, in forward
    out = self.inner(*trace_inputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/retinanet/model.py", line 104, in forward
    features.extend(backbone(x))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 479, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/retinanet/backbones/fpn.py", line 44, in forward
    p4 = F.interpolate(p5, scale_factor=2) + p4
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py", line 2512, in interpolate
    return torch._C._nn.upsample_nearest2d(input, _output_size(2))
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 3.95 GiB total capacity; 2.96 GiB already allocated; 25.06 MiB free; 36.28 MiB cached)
```
Is there a way to reduce the memory requirements for this processing?

My GPU is GeForce GTX 1050 Ti with Max-Q Design.

The size of the model file (.pth) I'm attempting to convert/export is 212MB.

Thanks in advance for any comments or suggestions.

**Comment by monocongo** [comment]
I resolved this issue by running the process on an EC2 (p3.2xlarge) instance instead. Sometimes you just need a bigger boat.

**Comment by monocongo** [comment]
This is maybe not the optimal solution, as it appears that you need to generate the *.plan file on the same system where the inference will be performed, as TensorRT performs device-specific profiling and optimizations to determine the best path for the particular hardware (at least according to [this](https://devtalk.nvidia.com/default/topic/1029737/jetson-tx1/tensorrt-saving-models-as-portable-plan-files/)). This is somewhat borne out by my experience using the serialized engine on my local machine after building it on the EC2 instance mentioned above:
```bash
The engine plan file is generated on an incompatible device, expecting compute 6.1 got compute 7.0, please rebuild.
Segmentation fault (core dumped)
```
Is it possible that I can update the Docker container (nvcr.io/nvidia/pytorch:19.05-py3) on my local machine to use "compute 7.0"? What does that refer to (the CUDA toolkit version, perhaps)? I assume this happened as a result of a version incompatibility between the GPU on the EC2 instance where the .plan file was created and the GPU of my local machine where I'm running the inference?

**Comment by pkashinkunti** [comment]
Compute capability is an attribute of the GPU hardware, and is not modifiable. See this page to refer to the compute capability of different NVIDIA GPUs: https://developer.nvidia.com/cuda-gpus

Yes, part of the TensorRT optimization process uses device-specific optimizations and thus the resulting engines are not transferrable across different GPU types (mentioned in the inference README here: https://github.com/NVIDIA/retinanet-examples/blob/master/INFERENCE.md#exporting-trained-pytorch-model-to-tensorrt). If you want to run a TRT engine on your GTX1050Ti, you would need to also export it on the same GPU. 

Going back to your original question, if you are seeing out-of-memory errors like this, your options are:
* Reduce the input image size of the exported model by specifying `--size x y` in `retinanet export` (the default input size is 1280x1280)
* Potentially use a smaller backbone which requires less memory
